name: test
on: [push]
jobs:
  # Dependencies installation
  dependencies:
    runs-on: ubuntu-latests

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

  # Build project
  build:
    needs: dependencies
    runs-on: ubuntu-latests

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

  # Run all linters
  linters:
    needs: dependencies
    runs-on: ubuntu-latests

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run linter
        run: yarn test:eslint

  # Deploy project
  deploy:
    needs: build
    runs-on: ubuntu-latests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          cache: yarn

      - run: yarn install
      - run: yarn build
      - run: echo package has been published
